# Generated by Django 6.0.6 on 2026-06-16 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=200, unique=True)),
                ('url', models.URLField()),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('tone', models.CharField(blank=True, max_length=200)),
                ('topics', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scrape_summary', models.TextField(blank=True)),
                ('scrape_status', models.CharField(choices=[('pending', 'Pending'), ('crawling', 'Crawling'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('last_crawled', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField()),
                ('page_title', models.CharField(blank=True, max_length=500)),
                ('raw_text', models.TextField()),
                ('heading_structure', models.JSONField(default=list)),
                ('crawled_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_pages', to='websites.website')),
            ],
            options={
                'ordering': ['-crawled_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('twitter', 'Twitter/X'), ('blog', 'Blog (Website)')], max_length=30)),
                ('make_webhook_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_connections', to='websites.website')),
            ],
            options={
                'unique_together': {('website', 'platform')},
            },
        ),
    ]
