# Generated by Django 6.0.6 on 2026-06-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='avg_read_time',
            field=models.CharField(blank=True, default='4.0m', max_length=50),
        ),
        migrations.AddField(
            model_name='website',
            name='brand_colors',
            field=models.JSONField(default=list),
        ),
    ]
