# Generated by Django 6.0.6 on 2026-06-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_website_avg_read_time_website_brand_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='needs_crawl',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='website',
            name='style_guide',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
