# Generated by Django 6.0.6 on 2026-06-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_website_needs_crawl_website_style_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperesult',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scraperesult',
            name='categories_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scraperesult',
            name='comments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scraperesult',
            name='ctas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scraperesult',
            name='entities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scraperesult',
            name='image_alts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scraperesult',
            name='key_phrases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scraperesult',
            name='main_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scraperesult',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scraperesult',
            name='meta_title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='scraperesult',
            name='og_properties',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scraperesult',
            name='page_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='scraperesult',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scraperesult',
            name='readability_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scraperesult',
            name='sentiment_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
