# Generated by Django 6.0.6 on 2026-06-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0004_scraperesult_author_scraperesult_categories_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='contact_email',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='website',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='website',
            name='logo_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
