# Generated by Django 6.0.6 on 2026-06-18 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0005_website_contact_email_website_contact_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('blog', 'Blog'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('twitter', 'Twitter/X')], max_length=20)),
                ('title', models.CharField(blank=True, help_text='Optional title or headline', max_length=500)),
                ('content', models.TextField(help_text='Full content of the sample post')),
                ('file_name', models.CharField(blank=True, help_text='Original file name if uploaded', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this sample')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='websites.website')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['website', 'platform', 'is_active'], name='websites_sa_website_8b0221_idx')],
            },
        ),
    ]
