# Generated by Django 6.0.6 on 2026-06-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0006_samplecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
    ]
