# Generated by Django 6.0.6 on 2026-06-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0007_website_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='color',
            field=models.CharField(default='#095075', max_length=7),
        ),
    ]
