# Generated by Django 6.0.6 on 2026-06-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0008_alter_website_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialconnection',
            name='auth_payload',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='socialconnection',
            name='auth_type',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
