# Generated by Django 6.0.6 on 2026-06-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, default='Managing content for specialty brands at Cadence.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_title',
            field=models.CharField(default='Content Manager', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=models.CharField(default='(GMT+05:30) India (Kolkata)', max_length=100),
        ),
    ]
