# Generated by Django 6.0.6 on 2026-06-16 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('website_add', 'Website Added'), ('website_update', 'Website Updated'), ('website_delete', 'Website Deleted'), ('crawl_start', 'Crawl Started'), ('crawl_done', 'Crawl Completed'), ('content_idea_submit', 'Content Idea Submitted'), ('content_generated', 'Content Generated'), ('content_approved', 'Content Approved'), ('content_rejected', 'Content Rejected'), ('content_regenerated', 'Content Regenerated'), ('content_scheduled', 'Content Scheduled'), ('content_published', 'Content Published'), ('user_add', 'User Added'), ('user_update', 'User Updated'), ('user_delete', 'User Deleted'), ('social_connected', 'Social Account Connected')], max_length=50)),
                ('target_description', models.CharField(max_length=300)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('location_city', models.CharField(blank=True, max_length=100)),
                ('location_country', models.CharField(blank=True, max_length=100)),
                ('success', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
