# Generated by Django 6.0.6 on 2026-06-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('website_add', 'Website Added'), ('website_update', 'Website Updated'), ('website_delete', 'Website Deleted'), ('crawl_start', 'Crawl Started'), ('crawl_done', 'Crawl Completed'), ('content_idea_submit', 'Content Idea Submitted'), ('content_generated', 'Content Generated'), ('content_approved', 'Content Approved'), ('content_rejected', 'Content Rejected'), ('content_regenerated', 'Content Regenerated'), ('content_scheduled', 'Content Scheduled'), ('content_published', 'Content Published'), ('content_update', 'Content Updated'), ('user_add', 'User Added'), ('user_update', 'User Updated'), ('user_delete', 'User Deleted'), ('user_signup', 'User Signed Up'), ('social_connected', 'Social Account Connected')], max_length=50),
        ),
    ]
