# Generated by Django 6.0.6 on 2026-06-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentdraft',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contentdraft',
            name='cover_image',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
