# Generated by Django 6.0.6 on 2026-06-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_contentdraft_category_contentdraft_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentdraft',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
    ]
