# Generated by Django 6.0.6 on 2026-06-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_contentdraft_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentdraft',
            name='author_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contentdraft',
            name='custom_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
