# Generated by Django 6.0.6 on 2026-06-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_contentdraft_author_name_contentdraft_custom_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentdraft',
            name='banner_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
