# Generated by Django 6.0.6 on 2026-07-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_tokenusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentdraft',
            name='cover_image_public_url',
            field=models.URLField(blank=True, default='', help_text='Permanent public URL of cover image uploaded to imgbb. Used for social/blog publishing.', max_length=1000),
        ),
        migrations.DeleteModel(
            name='TokenUsage',
        ),
    ]
