# Generated by Django 6.0.6 on 2026-07-07 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_add_cover_image_public_url'),
        ('websites', '0009_socialconnection_auth_payload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('crawler_summary', 'Website Crawler & Tone Summary'), ('idea_generation', 'Content Idea Suggestions'), ('blog_generation', 'Blog Post Body Generation'), ('social_generation', 'Social Post Generation'), ('visual_strategy', 'Visual Strategy Generation'), ('prompt_engineering', 'DALL-E Prompt Engineering'), ('image_generation', 'DALL-E Image Generation')], max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=8, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_usages', to='websites.website')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
