# Generated by Django 6.0.6 on 2026-07-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_tokenusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentdraft',
            name='meta_title',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
