# Generated by Django 6.0.6 on 2026-07-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_contentdraft_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentdraft',
            name='include_cta',
            field=models.BooleanField(default=True, help_text='Whether Contact Us CTA was enabled for this draft'),
        ),
        migrations.AddField(
            model_name='contentdraft',
            name='include_infographics',
            field=models.BooleanField(default=True, help_text='Whether infographics were enabled for this draft'),
        ),
    ]
