# Generated by Django 6.0.6 on 2026-07-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_add_infographics_cta_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentidea',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contentdraft',
            name='cover_image',
            field=models.TextField(blank=True),
        ),
    ]
